# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multilevelapp.customer')),
                ('ename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
            bases=('multilevelapp.customer',),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multilevelapp.Emp')),
                ('sname', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
            ],
            bases=('multilevelapp.emp',),
        ),
    ]
