# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Py', 'Python'), ('Dj', 'Django'), ('API', 'REST API'), ('UI', 'UI')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'Hyderabad'), ('Bang', 'Bangalore'), ('Che', 'Chennai'), ('Pune', 'Pune')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('Morg', 'Morning'), ('Aftn', 'AfterNoon'), ('Evng', 'Evening'), ('Ngt', 'Night')], max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('batch_start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
