# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('student_location', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_proxy',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('proxyapp.student',),
        ),
    ]
